name: Update README with Language Usage

on:
  push:
    paths:
      - language-usage.md
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Read language usage
        id: read_usage
        run: |
          USAGE_CONTENT=$(...)  # creates escaped, single-line usage block
          echo "usage=$USAGE_CONTENT" >> $GITHUB_OUTPUT


      - name: Debug language usage content
        run: echo "${{ steps.read_usage.outputs.usage }}"


      - name: Update README.md
        run: |
          awk -v usage="${{ steps.read_usage.outputs.usage }}" '
            /<!-- LANGUAGE-USAGE-START -->/ {
              print;
              print "```";
              print usage;
              print "```";
              next
            }
            /<!-- LANGUAGE-USAGE-END -->/ { print; next }
            { print }
          ' README.md > README.md.tmp
          mv README.md.tmp README.md


      - name: Commit and push changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add README.md
          git diff --quiet && git diff --staged --quiet || git commit -m "Update README language usage"
          git push
