name: Update README with Language Usage

on:
  push:
    paths:
      - language-usage.md
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Read language usage
        id: read_usage
        run: |
          USAGE_CONTENT=$(awk '{ printf "%s\\n", $0 }' language-usage.md)
          echo "usage=$USAGE_CONTENT" >> $GITHUB_OUTPUT


      - name: Debug language usage content
        run: echo "${{ steps.read_usage.outputs.usage }}"


      - name: Update README.md
        run: |
          usage_content=$(awk '{ printf "%s\\n", $0 }' language-usage.md)
          start="<!-- START_SECTION:language-usage -->"
          end="<!-- END_SECTION:language-usage -->"
          esc_usage=$(printf '%s\n' "$usage_content" | sed 's/[&/\]/\\&/g')
          awk -v start="$start" -v end="$end" -v content="$esc_usage" '
            BEGIN { print_start=1 }
            {
              if ($0 ~ start) {
                print; print content; print_start=0; skip=1; next
              }
              if ($0 ~ end) { print_start=1; skip=0 }
              if (print_start && !skip) print
              if ($0 ~ end) print
            }
          ' README.md > README.tmp && mv README.tmp README.md


      - name: Commit and push changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add README.md
          git diff --quiet && git diff --staged --quiet || git commit -m "Update README language usage"
          git push
