name: Update Language Usage Card

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  update-stats:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Clean temp_repos folder
        run: rm -rf temp_repos/

      - name: Install cloc
        run: sudo apt-get install cloc -y

      - name: Install dependencies
        run: pip install requests

      - name: Run stats script
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: python scripts/update_card.py

      - name: Commit and push changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add language-usage.md
          git diff --quiet && git diff --staged --quiet || git commit -m "Update language usage card"
          git push

