name: Update Language Usage Card

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  update-card:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install cloc
        run: sudo apt-get install cloc -y

      - name: Install dependencies
        run: pip install requests

      - name: Run stats script
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          python scripts/update_card.py

      - name: Commit and push changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add .
          git diff --quiet && git diff --staged --quiet || git commit -m "Update language usage card"
          git push
