name: Update README with Language Usage

on:
  push:
    paths:
      - language-usage.md
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate formatted usage block
        id: format_usage
        run: |
          echo 'usage<<EOF' >> $GITHUB_OUTPUT

          grep -E '\[[0-9]+\.[0-9]+%\]' language-usage.md |
          awk '
            match($0, /\[([0-9.]+)%\]/, m) {
              lang = substr($0, 1, RSTART - 2);
              pct = m[1] + 0;
              if (pct >= 1) {
                usage[lang] = pct;
                total++;
                if (pct > max_pct) max_pct = pct;
              }
            }
            END {
              n = asorti(usage, sorted, "@val_num_desc");
              limit = (n < 10 ? n : 10);

              printf "### 📊 **Weighted Language Usage**\n\n\`\`\`\n";
              for (i = 1; i <= limit; i++) {
                lang = sorted[i];
                pct = usage[lang];
                barlen = int((pct / max_pct) * 10);
                bar = "";
                for (j = 0; j < barlen; j++) bar = bar "█";
                printf "%-22s [%4.1f%%] %s\n", lang, pct, bar;
              }
              print "```";
            }
          ' >> $GITHUB_OUTPUT

          echo 'EOF' >> $GITHUB_OUTPUT

      - name: Update README.md
        run: |
          usage_content="${{ steps.format_usage.outputs.usage }}"
          echo -e "$usage_content" > usage_content.txt
          start="<!-- START_SECTION:language-usage -->"
          end="<!-- END_SECTION:language-usage -->"

          awk -v start="$start" -v end="$end" '
            BEGIN {
              while ((getline line < "usage_content.txt") > 0) {
                content = content line "\n"
              }
              close("usage_content.txt")
              print_section = 1
            }
            {
              if ($0 ~ start) {
                print
                printf "%s", content
                print_section = 0
                skip = 1
                next
              }
              if ($0 ~ end) {
                print_section = 1
                skip = 0
              }
              if (print_section && !skip)
                print
              if ($0 ~ end)
                print
            }
          ' README.md > README.tmp && mv README.tmp README.md

          rm usage_content.txt

      - name: Commit and push changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add README.md
          git diff --quiet && git diff --staged --quiet || git commit -m "Update README language usage"
          git push
